version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: psql_tienda_informatica
    restart: always
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=tienda_informatica
      - POSTGRES_USER=harri_pax
      - POSTGRES_PASSWORD=toor
    volumes:
      - ./postgres_data:/val/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_tienda_informatica
    restart: always
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mail.com
      - PGADMIN_DEFAULT_PASSWORD=toor
volumes:
  postgles_data: